name: Lab2 CI
on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 빌드 타입
        type: choice
        options:
          - Release
          - Debug
        default: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "빌드 타입은 ${{ inputs.build_type }}"
    